spring:
  application:
    name: BeyondGrain
  datasource:
#    url: jdbc:postgresql://localhost:5432/beyondgrain #local
    url: jdbc:postgresql://root:rnLsO1GPrJ1uhjqXVwNuSlsu3MQm2LYx@dpg-cq2jc4bv2p9s73eu7bm0-a.oregon-postgres.render.com/beyond_grain_db #prod
    username: root
    password: rnLsO1GPrJ1uhjqXVwNuSlsu3MQm2LYx
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      jwt-expiration: 86400000 # a day
      refresh-expiration: 604800000 # 7 days