spring:
  application:
    name: BeyondGrain
  data:
    mongodb:
      uri: mongodb+srv://itsdevem:itsdevem@beyond-grain.bmvh4v8.mongodb.net/beyond-grain
      database: beyond-grain-db
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      jwt-expiration: 86400000 # a day
      refresh-expiration: 604800000 # 7 days